# name: ğŸš€ Release

# on:
#   push:
#     branches:
#       - main

# jobs:

#   publish:
#     name: ğŸš€ Publish to NPM
#     runs-on: ubuntu-latest

#     env:
#       ACTIONS_ALLOW_UNSECURE_COMMANDS: true

#     steps:

#       - name: ğŸ“š Checkout
#         uses: actions/checkout@v4

#       - name: âš™ï¸ Setup Environment and Dependencies
#         uses: ./.github/actions/setup-environment-n-deps

#       - name: ğŸ§± Build (tsup)
#         run: pnpm build

#       - name: ğŸš€ Publish to NPM
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
